# Generated by Django 4.0.6 on 2022-07-11 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plataforma.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('nquartos', models.IntegerField()),
                ('nbanheiros', models.IntegerField()),
                ('data', models.CharField(max_length=100)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to=plataforma.models.filepath)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
