# Generated by Django 4.0.6 on 2022-07-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='cUser',
            new_name='cId',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='idUser',
        ),
    ]
