# Generated by Django 4.0.6 on 2022-07-12 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_rename_cuser_comentarios_cid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='cId',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.imovel_dois'),
        ),
    ]
