# Generated by Django 4.0.6 on 2022-07-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_remove_comentarios_cid_comentarios_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='cid',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='cids',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
