# Generated by Django 4.0.6 on 2022-07-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_remove_comentarios_cid_comentarios_cids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=200)),
                ('uid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
