# Generated by Django 4.0.6 on 2022-07-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='uid',
        ),
        migrations.AddField(
            model_name='share',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
